/**
 * @file bsp_BuzzerSongs.c
 * @brief 蜂鸣器歌曲 C语言版
 */

#include "bsp_BuzzerSongs.h"
#include "bsp_buzzer.h"

#define BUZZER_SONG_DEFAULT_UNIT_MS   200U
#define BUZZER_SONG_DEFAULT_VOL       1.0f

#define SONG_NOTE(freq, beat_val)     { (freq), (beat_val) }
#define SONG_REST(beat_val)           { 0.0f, (beat_val) }

// ====================== GALA《你》 ======================
static const BuzzerSongNote_t BuzzerSong_Gala_You[] =
{
    SONG_NOTE(BUZZER_FREQUENCY_B4, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1), SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_B4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_B4, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1), SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_B4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_B4, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1), SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_B4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_B4, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1), SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 6), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_C5, 4), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 6), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_C5, 8),

    SONG_NOTE(BUZZER_FREQUENCY_B4, 2), SONG_NOTE(BUZZER_FREQUENCY_D5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 10),

    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_C5, 4), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 6), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_C5, 4), SONG_NOTE(BUZZER_FREQUENCY_D5, 10),

    SONG_REST(4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_C5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_B3, 2), SONG_NOTE(BUZZER_FREQUENCY_A3, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 5),

    SONG_REST(1),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4),

    SONG_REST(1),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_REST(0.05f),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_A3, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_A3, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_C4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 6), SONG_REST(2),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 6), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 3), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 6),

    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 4), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 3), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_REST(0.1f), SONG_NOTE(BUZZER_FREQUENCY_G4, 3),
    SONG_REST(0.1f), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 8),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 6), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 3), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 6),

    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 6), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 3), SONG_NOTE(BUZZER_FREQUENCY_C5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2), SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_B4, 1), SONG_NOTE(BUZZER_FREQUENCY_C5, 12),

    SONG_REST(4),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 1), SONG_NOTE(BUZZER_FREQUENCY_E4, 3),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_C5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 1), SONG_NOTE(BUZZER_FREQUENCY_E4, 3),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_B3, 2),
    SONG_NOTE(BUZZER_FREQUENCY_A3, 1), SONG_NOTE(BUZZER_FREQUENCY_G3, 5),

    SONG_REST(1),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_G3, 1), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 3), SONG_NOTE(BUZZER_FREQUENCY_D4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4),

    SONG_REST(1),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_REST(0.2f),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_A3, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_A3, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_C4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 10),

    SONG_REST(4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 6), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 3), SONG_NOTE(BUZZER_FREQUENCY_B4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 6),

    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 5), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 2), SONG_NOTE(BUZZER_FREQUENCY_G4, 1),
    SONG_REST(0.2f), SONG_NOTE(BUZZER_FREQUENCY_G4, 3),
    SONG_REST(0.1f), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_REST(0.1f), SONG_NOTE(BUZZER_FREQUENCY_D4, 8),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 4), SONG_REST(1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 3), SONG_NOTE(BUZZER_FREQUENCY_D5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 6),

    SONG_NOTE(BUZZER_FREQUENCY_C4, 2), SONG_NOTE(BUZZER_FREQUENCY_D4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2), SONG_NOTE(BUZZER_FREQUENCY_C5, 4),
    SONG_NOTE(BUZZER_FREQUENCY_A4, 5),

    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_A4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 1), SONG_NOTE(BUZZER_FREQUENCY_A4, 3),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 4), SONG_NOTE(BUZZER_FREQUENCY_D5, 6),

    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 2), SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D4, 1), SONG_NOTE(BUZZER_FREQUENCY_C4, 12),

    // 灏惧
    SONG_REST(4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),

    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_G4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_C4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_G4, 4), SONG_NOTE(BUZZER_FREQUENCY_F4, 4),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 4), SONG_NOTE(BUZZER_FREQUENCY_D4, 4),
};

// ====================== 教父 ======================
static const BuzzerSongNote_t BuzzerSong_Godfather[] =
{
      SONG_NOTE(BUZZER_FREQUENCY_G3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G3_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A3_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G3,       5),

    SONG_NOTE(BUZZER_FREQUENCY_G3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_F3_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_F3,       5),

    SONG_NOTE(BUZZER_FREQUENCY_F3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G3_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4,       5),
    SONG_NOTE(BUZZER_FREQUENCY_F3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G3_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_B3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       4),

    SONG_NOTE(BUZZER_FREQUENCY_C4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_D4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_A4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_B3,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C4,       5),

    SONG_NOTE(BUZZER_FREQUENCY_C5,       1),
    SONG_NOTE(BUZZER_FREQUENCY_C5,       1),
    SONG_NOTE(BUZZER_FREQUENCY_B4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_A4_SHARP, 3),
    SONG_NOTE(BUZZER_FREQUENCY_A4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5,       2),
    SONG_NOTE(BUZZER_FREQUENCY_C5,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       4),

    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_A4_SHARP, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_F4,       3),
    SONG_NOTE(BUZZER_FREQUENCY_F4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G4_SHARP, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_F4,       1),
    SONG_NOTE(BUZZER_FREQUENCY_G4,       4),
};

// ====================== See You Again ======================
static const BuzzerSongNote_t BuzzerSong_See_You_Again[] =
{
  SONG_NOTE(BUZZER_FREQUENCY_G4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_G4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_G4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),

    SONG_NOTE(BUZZER_FREQUENCY_G4, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E4, 2),
    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 2),

    SONG_NOTE(BUZZER_FREQUENCY_A5, 6),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 6),
    SONG_REST(3),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 4),
    SONG_REST(2),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_B5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_A5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),

    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_REST(5),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A5, 6),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 6),
    SONG_REST(3),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 2),
    SONG_REST(4),
    SONG_NOTE(BUZZER_FREQUENCY_D5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_E5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 2),

    SONG_NOTE(BUZZER_FREQUENCY_A5, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_C6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D6, 2),
    SONG_REST(4),
    SONG_NOTE(BUZZER_FREQUENCY_G5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_A5, 1),
    SONG_NOTE(BUZZER_FREQUENCY_C6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_E6, 2),
    SONG_NOTE(BUZZER_FREQUENCY_D6, 2),
    SONG_REST(8),};

/**
  * @brief  播放歌曲
  */
void BuzzerSongs_Play(const BuzzerSongNote_t *song, uint32_t note_num, uint32_t unit_ms, float loudness)
{
    if (song == NULL || note_num == 0U)
        return;

    for (uint32_t i = 0; i < note_num; i++)
    {
        uint32_t duration_ms = (uint32_t)(song[i].beat * unit_ms);

        if (song[i].frequency <= 0.0f)
        {
            BSP_Buzzer_PlayNote(0.0f, duration_ms, 0.0f, 0);
        }
        else
        {
            BSP_Buzzer_PlayNote(song[i].frequency, duration_ms, loudness, 0);
        }
    }
}

void BuzzerSongs_Play_Gala_You(void)
{
    BuzzerSongs_Play(BuzzerSong_Gala_You,
                     sizeof(BuzzerSong_Gala_You)/sizeof(BuzzerSong_Gala_You[0]),
                     BUZZER_SONG_DEFAULT_UNIT_MS,
                     BUZZER_SONG_DEFAULT_VOL);
}

void BuzzerSongs_Play_Godfather(void)
{
    BuzzerSongs_Play(BuzzerSong_Godfather,
                     sizeof(BuzzerSong_Godfather)/sizeof(BuzzerSong_Godfather[0]),
                     400U, 1.0f);
}

void BuzzerSongs_Play_See_You_Again(void)
{
    BuzzerSongs_Play(BuzzerSong_See_You_Again,
                     sizeof(BuzzerSong_See_You_Again)/sizeof(BuzzerSong_See_You_Again[0]),
                     125U, 1.0f);
}